[files]
extend-exclude = [
	"SwiftIntro.xcodeproj/project.pbxproj",
	"SwiftIntro/Features/GameOver/GameOver.xcstrings",
	"SwiftIntro/Features/Game/View/Game.xcstrings",
	"SwiftIntro/Features/Settings/Settings.xcstrings",
	"SwiftIntro/Features/Loading/Loading.xcstrings",
]

[default.extend-identifiers]
udid = "udid"
UDID = "UDID"